site_name: Assertive
site_url: https://example.com/

theme: material

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
- Home: index.md
- Criteria: criteria/

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - mkdocstrings
  - gen-files:
      scripts:
        - docs/scripts/gen_criteria_pages.py
  - literate-nav:
      nav_file: SUMMARY.md