name: Release

on:
  workflow_dispatch

permissions:
  # Required for tagging
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.4.0

      - name: Verify main branch
        run: |
          if [[ "$(git branch --show-current)" != "main" ]]; then
            echo "This workflow is only allowed on the main branch.";
            exit 1;
          fi

      - name: Set up Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Extract version from pyproject.toml
        id: get_version
        run: echo "PACKAGE_VERSION=$(poetry version -s)" >> $GITHUB_ENV

      - name: Publish package on PyPI
        run: |
          poetry publish --build -u __token__ -p ${{ secrets.PYPI_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Create Git tag
        run: git tag v${{ env.PACKAGE_VERSION }}

      - name: Push tag
        run: git push origin v${{ env.PACKAGE_VERSION }}